version: '3.2'
services:
  legacywebshop:
    build:
      context: /monolith
      dockerfile: docker/Dockerfile
    ports:
      - "8888:8080"
    networks:
        local_dev_net:
            aliases:
               - legacywebshop

  web-shop-db-image:
    build:
      context: /monolith
      dockerfile: docker/DockerfileMySQL
    volumes:
      - ./monolith/sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: c8de110f37300a53a971749
      MYSQL_USER: webshopuser
      MYSQL_PASSWORD: 240b2c6d58ff2ce2f508b49f
    ports:
      - "3306:3306"
    networks:
        local_dev_net:
            aliases:
                - web-shop-db-image

  categories:
    container_name: categories
    build:
      context: categories
      dockerfile: Dockerfile
    image: vsys:categories
    ports:
      - "8082:8082"
    networks:
        local_dev_net:
            aliases:
               - categories-service

  cSharpTest:
    container_name: cSharpTest
    build:
      context: products_csharp/dotnet-6-crud-api
      dockerfile: Dockerfile
    image: test:products
    ports:
      - "4000:4000"
    networks:
        local_dev_net:
            aliases:
               - products-service
networks:
  local_dev_net:
    driver: bridge
